[package]
name = "solana-geyser-mock"
version = "0.1.0"
edition = "2024"

[dependencies]
yellowstone-grpc-proto = "12.4.0"
yellowstone-grpc-client = "13.1.0"

tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-util = "0.7.18"
tokio-stream = "0.1.18"
futures = "0.3.32"
async-trait = "0.1"


solana-pubkey = "3"
solana-signature = "3"

rand = { version = "0.8", default-features = false, features = [
    "std",
    "std_rng",
] }
tracing = "0.1.44"
thiserror = "1"
bs58 = "0.5.1"
base64 = "0.22.1"
